name: Release
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run"
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build chiseledPublishMods
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          PUBLISH_DRY_RUN: ${{ github.event.inputs.dry_run == 'true' && '1' || '' }}